package com.persional.retrofitposttingtest.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.persional.retrofitposttingtest.db.entity.Inspect;

import com.persional.retrofitposttingtest.db.InspectDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig inspectDaoConfig;

    private final InspectDao inspectDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        inspectDaoConfig = daoConfigMap.get(InspectDao.class).clone();
        inspectDaoConfig.initIdentityScope(type);

        inspectDao = new InspectDao(inspectDaoConfig, this);

        registerDao(Inspect.class, inspectDao);
    }
    
    public void clear() {
        inspectDaoConfig.clearIdentityScope();
    }

    public InspectDao getInspectDao() {
        return inspectDao;
    }

}
